language: node_js
node_js:
- '7'
- '10'
script:
- npm run deploy
env:
  global:
    secure: tlM+QEVU2H8tsviCwobtGfuudeOEAhHQ3Nkge3q5laPzrizGqyqvzRMpxFCdkbREH9m0+kR/1AX4pbC2ipNV0dZNZlDEiFuETTSFccEJuq4AVKgLE1RcTNuoHd02eeCa3/aVdphqqoXG8owDLzLLq06NM3qv+MXlqJGEiWkIWYZ0R2Shf2102fT8gmUVfvSdmYJQoRt2Js1dZc2iB1ENuZ9/dbQD151RUFAe8wUzLCBMVdNADkP/H80ugD8FF8FMtDg6TcPvhKJWzsu7rxxC7OJglGTasHuIhzQNtIGwbSYJDOQPK8hgVQRV+KmnP9fcXh8O1SiVvfsUVd2kJOfq+hhrw/TaC99uHGZBGhk2KciRLq9YWh/nJBfz/8Bqv0IdG1wr/7/djIzM+c3AYnFpLyQnTCRXLPMV52IByMPxY3m1BjizM8SuSoh+cP7CpABUYZg8xDN7BdOCaSly3cpiLh3KxT/VJBMFOHGwrbyI49JvbnLYUsA71xJ3yhntdvemXGXSNYjtpMruVBEhywylXoGOalUrHsf3NT3xN+2tsq/03jiZJcSeSS5C29Idbj8scK85EfnKoeLJTkyocbp4gzhaIrKuv0pWvzICMUMON2ITB0+NAyNaQoHtvNo4D0KLYmss2+lu9nTEdXDZkOmPkCHwLPjIdgRFaYipUlF8ulY=
